services:
  web:
    container_name: xgb-bitcoin-direction-local
    build:
      context: .
      dockerfile: deploy/prod_server/Dockerfile
    image: xgb-bitcoin-direction:local
    ports:
      - "9743:9743"
    volumes:
      - ./models:/app/models:ro
      - ./data/crypto_data.db:/app/crypto_data.db
      - ./static:/app/static
    restart: unless-stopped
